// <auto-generated />
namespace Origin.YMC.Business.Entities.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class TestimonialModel : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(TestimonialModel));
        
        string IMigrationMetadata.Id
        {
            get { return "201910041809400_TestimonialModel"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
